#!/usr/bin/env python


def sum_squares(numbers):
    return sum(i ** 2 for i in numbers)


def square_sum(numbers):
    return sum(numbers) ** 2


def main():
    k = range(1, 101)
    print(square_sum(k) - sum_squares(k))


if __name__ == "__main__":
    main()
