#!/usr/bin/env python

from math import sqrt
from itertools import count


def is_prime(number):
    if number in [0, 1]:
        return False
    for i in range(2, int(sqrt(number)) + 1):
        if (number % i) == 0:
            return False
    return True


def primes():
    return (i for i in count(2) if is_prime(i))


def nth_prime(n):
    i = 0
    for prime in primes():
        i += 1
        if i >= n:
            return prime


def main():
    print(nth_prime(10001))


if __name__ == "__main__":
    main()
