#!/usr/bin/env python


def main():
    print(n_triangles(500))


def n_triangles(divisors):
    i = 1
    while True:
        n = int(i * (i + 1) / 2)
        if num_factors(n) > divisors:
            return n
        i += 1


def num_factors(n):
    s = 0
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            s += 1
    return s * 2 + 2


if __name__ == "__main__":
    main()
