#!/usr/bin/env python


def main():
    print(sum(diagonals()))


def diagonals():

    yield 1

    dx = 2
    start = 1 + dx
    end = start + (4 - 1) * dx

    for i in range(start, end + 1, dx):
        # print(i)
        yield i

    for k in range(int((1001 - 3) / 2)):
        dx += 2
        start = end + dx
        end = start + (4 - 1) * dx

        for i in range(start, end + 1, dx):
            # print(i)
            yield i


if __name__ == "__main__":
    main()
