#!/usr/bin/env python


def main():
    # we don't need to check 7 digit numbers because 9_999_999 > 413_343
    # i experimentally reduced the max to 200_000
    # this results in the same answer as an upper bound of 9_999_999
    s = sum(i for i in range(2, 200_000) if i == get_fpds(i))
    print(s)


def get_fpds(n):
    """
    checks if number is a fifth power digit sum
    """
    return sum(fifth_power[i] for i in str(n))


fifth_power = {
    "0": 0,
    "1": 1,
    "2": 32,
    "3": 243,
    "4": 1024,
    "5": 5 ** 5,
    "6": 6 ** 5,
    "7": 7 ** 5,
    "8": 8 ** 5,
    "9": 9 ** 5,
}

if __name__ == "__main__":
    main()
