#!/usr/bin/env python

from tools import sieve


def main():
    num = sum(get_interesting_primes(1_000_000))
    print(num)


def get_interesting_primes(n):
    primes = set(sieve(n))
    for i in primes - {2, 3, 5, 7}:
        truncations = set(get_truncations(i))
        if all(i in primes for i in truncations):
            yield i


def get_truncations(i):
    yield int(i)
    for j in range(1, len(str(i))):
        yield int(str(i)[j:])
        yield int(str(i)[:j])


if __name__ == "__main__":
    main()
