#!/usr/bin/env python


def main():
    r = range(999 ** 2, 100 ** 2 - 1, -1)
    lp = largest_palindrome(r)
    print(lp)


def largest_palindrome(r):
    for i in r:
        if is_palindromic(i) and factorize(i):
            return i


def factorize(n):
    for i in range(100, int(n ** 0.5) + 1):
        if n % i == 0 and len(str(n // i)) == 3:
            return True
    return False


def is_palindromic(n):
    s = str(n)
    return s == s[::-1]


if __name__ == "__main__":
    main()
