#!/usr/bin/env python


def main():
    # r = list(range(1, 10 + 1))
    r = list(range(1, 20 + 1))
    print(lcm_m(r))


def lcm(a, b):
    g, l = max(a, b), min(a, b)
    for i in range(1, l + 1):
        if (g * i) % l == 0:
            return g * i


def lcm_m(r):
    if len(r) == 2:
        return lcm(*r)
    return lcm(lcm_m(r[: len(r) - 1]), r[-1])


if __name__ == "__main__":
    main()
