#!/usr/bin/python3

numbers = {
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve",
    13: "thirteen",
    14: "fourteen",
    15: "fifteen",
    16: "sixteen",
    17: "seventeen",
    18: "eighteen",
    19: "nineteen",
    20: "twenty",
    30: "thirty",
    40: "forty",
    50: "fifty",
    60: "sixty",
    70: "seventy",
    80: "eighty",
    90: "ninety",
}


def main():
    print(sum_letters(range(1, 1001)))


def sum_letters(r):
    s = 0
    for i in r:
        s += len(to_string(i).replace(" ", ""))
    return s


def to_string(n):

    if n // 10 < 2:
        return numbers[n]

    if n // 10 >= 2 and n // 10 < 10:
        k1 = (n // 10) * 10
        k2 = n % 10

        if k2 == 0:
            return numbers[k1]

        return f"{numbers[k1]} {numbers[k2]}"

    if n // 10 >= 10 and n // 10 < 100:
        k1 = n // 100
        k2 = n % 100

        if k2 == 0:
            return f"{numbers[k1]} hundred"

        return f"{numbers[k1]} hundred and {to_string(k2)}"

    if n == 1000:
        return "one thousand"


if __name__ == "__main__":
    main()
