#!/usr/bin/env python

from itertools import permutations


def main():
    print(get_nth_perm(range(0, 9 + 1), 1_000_000))


def get_nth_perm(l, n):
    count = 1
    for k in permutations(l):
        if count == n:
            return k
        count = count + 1


if __name__ == "__main__":
    main()
