#!/usr/bin/env python


def main():
    print(solution())


def solution():
    """
    this alternate solution is an implementation of RogerHui's method
    """
    r1 = range(1, 10 ** 1)
    r2 = range(1, 10 ** 4)

    s1 = {i * j for i in r1 for j in r2 if is_valid(i, j)}

    r3 = range(1, 10 ** 2)
    r4 = range(1, 10 ** 3)

    s2 = {i * j for i in r3 for j in r4 if is_valid(i, j)}

    return sum(s1.union(s2))


def is_valid(i, j):
    return "".join(sorted(str(i) + str(j) + str(i * j))) == "123456789"


if __name__ == "__main__":
    main()
