#!/usr/bin/env python

import itertools


def main():
    s = "123456789"
    print(f"{s=}")

    s1 = sum({z for i in get_permutations(s) for z in get_identity(i)})
    print(s1)


def get_permutations(s):
    return itertools.permutations(s)


def get_identity(s):
    for a in range(1, len(s)):
        for b in range(a, len(s) - 1):
            x, y, z = (
                int("".join(s[:a])),
                int("".join(s[a : b + 1])),
                int("".join(s[b + 1 :])),
            )
            if x * y == z:
                yield z


if __name__ == "__main__":
    main()
