#!/usr/bin/env python

from tools import sieve


def main():
    n = 1_000_000
    primes = set(sieve(n))
    num = sum(1 for i in primes if is_circular_prime(i, primes))
    print(num)


def is_circular_prime(n, primes):
    s = set(str(n))
    d = [0, 2, 4, 5, 6, 8]
    if any(i in s for i in d):
        return False
    return all((i in primes) for i in get_rotations(n))


def get_rotations(n):
    s = str(n)
    for i in range(len(s)):
        yield int(s[i:] + s[:i])


if __name__ == "__main__":
    main()
